project/main/urls.py
from django import views
from django.urls import include, path
from. import views

app_name="main"

urlpatterns = [
    path('home/',views.home,name='home_page'),
    path('article/',views.article_details,name='article_details'),
    path('sumaiya-sani/',views.my_cv,name='my_cv'),
   
]

project/project/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('main.urls',)),

]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

project/main/models.py
from django.db import models

# Create your models here.

project/main/views.py
from fileinput import filename
from importlib.resources import contents
from urllib import response
from django.forms import FilePathField
from django.shortcuts import render
import mimetypes
import os
from django.http import StreamingHttpResponse
from wsgiref.util import FileWrapper
from django.http.response import HttpResponse


def home(request):

    return render(request,'home.html')


def article_details(request):

    return render(request,'article_details.html')

def my_cv(request):
    return render(request,'cv.html')


#downoload

  # Define function to download pdf file using template
def download_file(request, filename=''):
    if filename != '':
        # Define Django project base directory
        BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
        # Define the full file path
        filepath = BASE_DIR + '/main/files/' + filename
        # Open the file for reading content
        path = open(filepath, 'rb')
        # Set the mime type
        mime_type, _ = mimetypes.guess_type(filepath)
        # Set the return value of the HttpResponse
        response = HttpResponse(path, content_type=mime_type)
        # Set the HTTP header for sending to browser
        response['Content-Disposition'] = "attachment; filename=%s" % filename
        # Return the response value
        return response
    else:
        # Load the template
        return render(request, 'cv.html')









 

project/main/templates/article_details.html
{% extends 'base.html '%}
{% load static %}



{% block content %}


<!-- into -->

<section>
    <div class="container text-center">
        <div class="py-5  align-item-center justify-content-center">
            
            <h1> title of the article </h1>
            <h3> name of the author </h3>
            <p> date of published </p>
            <img  class="img-fluid py-5" style="width:900px;" src="{% static 'img/blog_art/undraw_phone_call_re_hx6a.svg' %}" alt="">   
        </div>
    
    
    
    </div>

    <!-- article -->
    <section class="py-5">
        <div class="container">
            <div class="row col-12 ">
                <div class="col-12  pl-lg-4 mbr-text mbr-fonts-style display-7">
                <h3> Lorem, ipsum dolor sit amet consectetur adipisicing elit. Autem vitae maxime quibusdam mollitia quisquam deleniti earum, quod tempore minima ab? Velit eos laudantium iste voluptatibus! Eligendi amet placeat sit. Repellat veniam temporibus magni excepturi alias, libero, error quo labore nihil illum soluta maxime repellendus? Minima quae esse impedit dolor rem? </h3>
                </div>
                
                
                <h5> Lorem ipsum dolor sit amet consectetur adipisicing elit. Iure accusamus harum officiis illum quibusdam, consequatur tempore, vitae aliquam explicabo in ea fugiat eius id quo, saepe ut dolorem deleniti! Tempora at repudiandae laborum inventore, explicabo magnam rem, eos voluptatem distinctio sunt corporis quisquam minus possimus veniam. Modi quas cumque ad?</h5>

            </div>
            <div class="col-12  pl-lg-4 mbr-text mbr-fonts-style display-7">
                <h3> Lorem, ipsum dolor sit amet consectetur adipisicing elit. Autem vitae maxime quibusdam mollitia quisquam deleniti earum, quod tempore minima ab? Velit eos laudantium iste voluptatibus! Eligendi amet placeat sit. Repellat veniam temporibus magni excepturi alias, libero, error quo labore nihil illum soluta maxime repellendus? Minima quae esse impedit dolor rem? </h3>
                </div>
                
                
                <h5> Lorem ipsum dolor sit amet consectetur adipisicing elit. Iure accusamus harum officiis illum quibusdam, consequatur tempore, vitae aliquam explicabo in ea fugiat eius id quo, saepe ut dolorem deleniti! Tempora at repudiandae laborum inventore, explicabo magnam rem, eos voluptatem distinctio sunt corporis quisquam minus possimus veniam. Modi quas cumque ad?</h5>

                <div class="col-12  pl-lg-4 mbr-text mbr-fonts-style display-7">
                    <h3> Lorem, ipsum dolor sit amet consectetur adipisicing elit. Autem vitae maxime quibusdam mollitia quisquam deleniti earum, quod tempore minima ab? Velit eos laudantium iste voluptatibus! Eligendi amet placeat sit. Repellat veniam temporibus magni excepturi alias, libero, error quo labore nihil illum soluta maxime repellendus? Minima quae esse impedit dolor rem? </h3>
                    </div>
                    
                    
                    <h5> Lorem ipsum dolor sit amet consectetur adipisicing elit. Iure accusamus harum officiis illum quibusdam, consequatur tempore, vitae aliquam explicabo in ea fugiat eius id quo, saepe ut dolorem deleniti! Tempora at repudiandae laborum inventore, explicabo magnam rem, eos voluptatem distinctio sunt corporis quisquam minus possimus veniam. Modi quas cumque ad?</h5>
    
                </div>
            </div>
            
        </div>
    </section>
</section>


{% endblock %}

project/main/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.13.0/css/all.min.css" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'custom.css' %}">
   
   
    
    <title>Document</title>
    
        

  
</head>
<body>
 <!-- navbar -->
 <div class="navbar navbar-expand-md navbar-light bg-light">
    <div class="container">
     <a href="#" class="navbar-brand">Sima blog </a>
     
    <button 
    class="navbar-toggler"
    type="button"
    data-bs-toggle="collapse" 
    data-bs-target="#main"
      > 
      <span class="navbar-toggler-icon"> </span></button>
     
    
    
    <div class="collapse navbar-collapse" id="main">


         <ul class="navbar-nav ms-auto" id="main">
             <li class="nav-item"><a href="{% url 'main:home_page' %}" class="nav-link"> Blog </a></li>
             <li class="nav-item"><a href="" class="nav-link"> about </a></li>
             <li class="nav-item"><a href="" class="nav-link"> Conract me</a></li>
         </ul>
        
     </div>

    </div>
</div>
{% block content %}




{% endblock %}





<!-- footer-->
<footer class="py-4 bg-light text-center position-relative">
    <div class="container">
        <p class="lead"> copyright &copy; 2022 Sumaiya Sani</p>
        <a href="#" class="position-absolute bottom-0 end-o p-3">
            <i class=" bi bi-arrow-up-circla h2"></i>
        </a>
    </div>

</footer>







<script src="vanilla-tilt.js">  </script> 

<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script> 
</body>
</html>

project/main/templates/blog.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="stylesheet" href="custom.css">
   
   
    
    <title>Document</title>
    
        

  
</head>
<body>
    <!-- navbar -->
<div class="navbar navbar-expand-md navbar-light bg-light">
    <div class="container">
     <a href="#" class="navbar-brand">Sima blog </a>
     
    <button 
    class="navbar-toggler"
    type="button"
    data-bs-toggle="collapse" 
    data-bs-target="#main"
      > 
      <span class="navbar-toggler-icon"> </span></button>
     
    
    
    <div class="collapse navbar-collapse" id="main">


         <ul class="navbar-nav ms-auto" id="main">
             <li class="nav-item"><a href="" class="nav-link"> Blog </a></li>
             <li class="nav-item"><a href="" class="nav-link"> category </a></li>
             <li class="nav-item"><a href="" class="nav-link"> Conract me</a></li>
         </ul>
        
     </div>

    </div>
</div>
    

    <div class="main_container">
        
        <div class="card" data-tilt>
            <img class="img1" src="img/blog_inter/woman.png" >
            <h2> Sumaiya Sani </h2>
            <p>backend developer usuing python </p>
            <div class="links">
                <a href="#"><img src="img/blog_inter/facebook.png" alt=""></a>
                <a href="#"><img src="img/blog_inter/twitter.png" alt=""></a>
                <a href="#"><img src="img/blog_inter/telegram.png" alt=""></a>
            </div> 
            <a href="#" class="btn"> Massage me </a>
    
        </div>  
    
    <div class="second_container">
        <h3> welcom to my blog ! Lorem ipsum dolor sit amet consectetur adipisicing elit. Enim suscipit aut ut accusantium, iusto quia. Laboriosam aliquid nisi accusantium nostrum cumque totam ullam asperiores eius ad, doloremque ipsam illum ducimus?</h3>
        <h3> Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptatibus facilis illo nihil. Id, quis? Excepturi dicta sed corrupti itaque architecto doloribus similique reprehenderit, ipsa aspernatur dolor magnam impedit laudantium illo debitis quasi eum, nobis temporibus veritatis praesentium quis officia delectus rem dolorum vitae! Nam, cum ratione commodi dolorem sunt accusantium?</h3>

    </div>
</div>

 <!-- the blog is start -->
 <section>
     
        
</section>

<!-- post-->

<script src="vanilla-tilt.js">  </script> 

<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script> 
</body>
</html>

project/main/templates/cv.html
{% extends 'base.html '%}
{% load static %}



{% block content %}
    
   
    <!-- Hero-->
    <section id="hero" class=" text-dark text-center py-5 text-lg-start">
        <div class="container">
            <div class="d-sm-flex align-items-center justify-content-center" >
                <div class="py-3">
                    <h1 class="display-5"> Hi <span class="text-info"> sumaiya is here  </span></h1>
                    <p class="py-1 lead"> Lorem ipsum dolor sit amet, consectetur adipisicing elit. Iste sunt aliquam temporibus rem cumque accusamus impedit ipsa quibusdam voluptas maxime, tempore expedita eum amet praesentium architecto? Eaque consequuntur nulla maiores et animi nesciunt eius adipisci ullam dolores sequi? Illum delectus fugiat ab nulla fuga eligendi incidunt voluptate aliquid ipsum in.</p>
                    <a herf="" > <button class="btn btn-info"> Download CV </button></a> 
                </div>
                <img class="img-fluid w-50" src="{% static 'img/main.svg' %}" alt="">
            </div>
        </div>

    </section>
    <!-- project -->
    <section class="py-5 bg-light ">
        
        <div class="container py-4">
           
               
                <h3 class="display-5"> Here what i do: </h3>
           
            <div class="row text-center align-items-center justify-content-center">
                <div class=" col col-sm ">
                    <div class="card bg-light" style="width: 18rem;">
                        <img src="{% static 'img/blog.svg' %}" class="card-img-top" alt="...">
                        <div class="card-body">
                          <p class="card-text py-1 text-dark">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
                          <button class="btn btn-info"> see more</button>
                        </div>
                      </div>
                </div>
                <div class="col col-sm">
                    <div class="card bg-light" style="width: 18rem;">
                        <img src="{% static 'img/ecommerce.svg' %}" class="card-img-top" alt="...">
                        <div class="card-body">
                          <p class="card-text py-1 text-dark">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
                          <button class="btn btn-info"> see more</button>
                        </div>
                      </div>
                </div>
                <div class="col col-sm">
                    <div class="card bg-light" style="width: 18rem;">
                        <img src="{% static 'img/ecommerce.svg' %}" class="card-img-top" alt="...">
                        <div class="card-body">
                          <p class="card-text py-1 text-dark">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
                          <button class="btn btn-info"> see more</button>
                        </div>
                      </div>
                </div>
               
            </div>
        </div>

    </section>
    <!-- blog -->


    <!-- contact me -->
    <section id="contact me" class="py-4">
        
        <div class="container">
            <div class="p-5">
                <h3 class="display-5"> CONTACT ME</h3>
                <h3> We can reach each other here :</h3>
            </div>
            <div class="row align-items-center justify-content-center">
                <div class="col-md">
                    <img style="width:600px;"  src="{% static 'img/social.svg' %} " alt="">
                </div>
                <div class="col-md py-5">
                  
                    <ul class="list-group list-group-flush">
                        <li class="list-group-item"><a
                            class="btn btn-primary btn-lg btn-floating"
                            style="background-color: #003566;"
                            href="#!"
                            role="button"
                            ><i class="fab fa-instagram"></i
                          > </a></i></li>
                        <li class="list-group-item"><li class="list-group-item"><a
                            class="btn btn-primary btn-lg btn-floating"
                            style="background-color: #003566;"
                            href="#!"
                            role="button"
                            ><i class="fab fa-twitter"></i
                          ></a></i></li>
                        <li class="list-group-item"><li class="list-group-item"><a
                            class="btn btn-primary btn-lg btn-floating"
                            style="background-color: #003566;"
                            href="#!"
                            role="button"
                            ><i class="fab fa-github"></i
                          ></a></i></li>
                        <li class="list-group-item"><li class="list-group-item"><a
                            class="btn btn-primary btn-lg btn-floating"
                            style="background-color: #003566;"
                            href="#!"
                            role="button"
                            ><i class="fab fa-google"></i
                          ></a></i></li>
                        <li class="list-group-item"><li class="list-group-item"><a
                            class="btn btn-primary btn-lg btn-floating"
                            style="background-color: #003566;"
                            href="#!"
                            role="button"
                            ><i class="fab fa-linkedin-in"></i
                          ></a></i></li>
                      </ul>

                </div>
            </div>
        </div>

    </section>
   

    
{% endblock %}

project/main/templates/home.html
{% extends 'base.html '%}
{% load static %}



{% block content %}

<!-- hero -->

<section id="hero" class=" text-dark text-center py-5 text-lg-start">
    <div class="container">
        <div class="d-sm-flex align-items-center justify-content-center" >
            <div class="py-3">
                <h1 class="display-5"> Hi <span class="text-warning"> sumaiya is here  </span></h1>
                <p class="py-1 lead"> Lorem ipsum dolor sit amet, consectetur adipisicing elit. Iste sunt aliquam temporibus rem cumque accusamus impedit ipsa quibusdam voluptas maxime, tempore expedita eum amet praesentium architecto? Eaque consequuntur nulla maiores et animi nesciunt eius adipisci ullam dolores sequi? Illum delectus fugiat ab nulla fuga eligendi incidunt voluptate aliquid ipsum in.</p>
                <button class="btn btn-info"> Download CV </button>
            </div>
            <img class="img-fluid w-50" src="{% static 'img/main.svg' %}" alt="">
        </div>
    </div>

</section>


<section class="introdection ">
    <div class="container mt-5">
    <h1 class="display-4">
        last post  
    </h1>
    <p class="fs-3 fw-light text-muted">
        my job 
    </p>
    <div class="row align-item-center">
        <div class="col-lg-6">
            <img src="{% static 'img/blog_inter/flower.jpg' %}" class="img-fluid rounded ">

        </div>
        <div class="col-lg-6 mt-lg-0 mt-5">
            <h3> About </h3>
            <p class="lead"> Lorem ipsum dolor sit amet, consectetur adipisicing elit. Minima, eius laboriosam. Aspernatur voluptatem odit, pariatur quasi numquam, ratione vel sint ipsum cumque, praesentium eius sed cum non fuga doloribus impedit vero voluptatibus tempora consequatur necessitatibus? Fuga aspernatur qui at, error adipisci obcaecati asperiores, commodi doloremque animi eaque consectetur explicabo veniam. </p>
        </div>
    </div>


    </div>

</section>
    <section class="feature bg-light">
        <div class="container">
            <h3 class="mt-5 mb-3 py-5"> Feature post</h3>
            <div class="row">
                <div class="col-lg-3 col-6">
                    <figure class="figure">
                        <img src="{% static 'img/blog_inter/plant.jpg' %}" class="figure-img img-fluid rounded" alt="...">
                        <figcaption class="figure-caption">A caption for the above image.</figcaption>
                        <a class="btn btn-primary btn-sm" href="#" role="button"> Read more</a>

                      </figure>

                </div> 
                <div class="col-lg-3 col-6">
                    <figure class="figure">
                        <img src="{% static 'img/blog_inter/plant.jpg' %}" class="figure-img img-fluid rounded" alt="...">
                        <figcaption class="figure-caption">A caption for the above image.</figcaption>
                      </figure>

                </div> 
                <div class="col-lg-3 col-6">
                    <figure class="figure">
                        <img src="{% static 'img/blog_inter/plant.jpg' %}" class="figure-img img-fluid rounded" alt="...">
                        <figcaption class="figure-caption">A caption for the above image.</figcaption>
                      </figure>

                </div> 
               <div class="col-lg-3 col-6">
                    <figure class="figure">
                        <img src="{% static 'img/blog_inter/plant.jpg' %}" class="figure-img img-fluid rounded" alt="...">
                        <figcaption class="figure-caption">A caption for the above image.</figcaption>
                      </figure>

                </div> 


            </div>
        </div>

    </section>

    {% endblock %}